### ISSUE TITLE
Every cross server connection will report an error，but it doesn't seem to affect the use. I don't know what the error is

### ISSUE THREAD

**Issue by xibo1212** [ZorgBtw/BungeeSK#10]
23:30:13 [信息] [danke] <-> DownstreamBridge <-> [war] has disconnected
23:30:33 [信息] [danke] <-> ServerConnector [Lobby] has connected
23:30:34 [警告] Error dispatching event ServerSwitchEvent(player=danke) to listener fr.zorg.bungeesk.bungee.listeners.ServSwitchEvent@f627d13
java.lang.NoSuchMethodError: net.md_5.bungee.api.event.ServerSwitchEvent.getFrom()Lnet/md_5/bungee/api/config/ServerInfo;
    at fr.zorg.bungeesk.bungee.listeners.ServSwitchEvent.onSwitch(ServSwitchEvent.java:13)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:397)
    at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:291)
    at net.md_5.bungee.protocol.packet.Login.handle(Login.java:87)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:104)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
    at java.lang.Thread.run(Unknown Source)

**Comment by ZorgBtw** [comment]
context please ?

**Comment by xibo1212** [comment]
[统一通行证] launched from premain
[统一通行证] 正在从服务器获取通行证配置信息: https://auth2.nide8.com:233/d857d2fdb1e311e89250525400b59b6a/
*** Warning, this build is outdated ***
*** Please download a new build from http://ci.md-5.net/job/BungeeCord ***
*** You will get NO support regarding this build ***
*** Server will start in 10 seconds ***
13:47:29 [信息] Using standard Java JCE cipher.
13:47:29 [信息] Using standard Java compressor.
13:47:29 [信息] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.14-SNAPSHOT:3ec223e:1412
13:47:29 [严重] [统一通行证] transform [https://sessionserver.mojang.com/session/minecraft/hasJoined?username=] to [https://auth2.nide8.com:233/d857d2fdb1e311e89250525400b59b6a/sessionserver/session/minecraft/hasJoined?username=]
13:47:29 [严重] [统一通行证] transform net.md_5.bungee.connection.InitialHandler using yggdrasil-api-transform
13:47:29 [信息] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
13:47:29 [信息] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
13:47:29 [信息] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
13:47:29 [信息] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
13:47:29 [信息] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
13:47:29 [信息] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
13:47:30 [信息] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.14-SNAPSHOT:3ec223e:1412 by SpigotMC
13:47:30 [信息] Loaded plugin BungeeSK version 1.0.3 by Zorg and Aless
13:47:30 [信息] Loaded plugin cmd_find version git:cmd_find:1.14-SNAPSHOT:3ec223e:1412 by SpigotMC
13:47:30 [信息] Loaded plugin BungeeKick version 1.2 by Vik1395
13:47:30 [信息] [KnapsackToGo] 开始初始化
13:47:30 [信息] [KnapsackToGo] 初始化完成，准备加载！
13:47:30 [信息] Loaded plugin KnapsackToGo version 2021.5.22 by jianjianai
13:47:30 [信息] Loaded plugin cmd_server version git:cmd_server:1.14-SNAPSHOT:3ec223e:1412 by SpigotMC
13:47:30 [警告] Error enabling plugin BungeeTabListPlus_BukkitBridge
java.lang.ClassNotFoundException: Do not install BungeeTabListPlus_BukkitBridge.jar on BungeeCord.
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:324)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:232)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:265)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
13:47:30 [信息] Loaded plugin cmd_alert version git:cmd_alert:1.14-SNAPSHOT:3ec223e:1412 by SpigotMC
13:47:30 [信息] Loaded plugin cmd_send version git:cmd_send:1.14-SNAPSHOT:3ec223e:1412 by SpigotMC
13:47:30 [信息] Loaded plugin cmd_list version git:cmd_list:1.14-SNAPSHOT:3ec223e:1412 by SpigotMC
13:47:30 [信息] Loaded plugin BungeeTabListPlus version 2.8.10 by CodeCrafter47
13:47:30 [警告] Forced host server pvp is not defined
13:47:30 [信息] [BungeeSK] BungeeSK has been successfully started !
13:47:30 [警告] MinecraftForge support is currently unmaintained and may have unresolved issues. Please use at your own risk.
13:47:30 [信息] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.14-SNAPSHOT:3ec223e:1412 by SpigotMC
13:47:30 [信息] Enabled plugin BungeeSK version 1.0.3 by Zorg and Aless
13:47:30 [信息] Enabled plugin cmd_find version git:cmd_find:1.14-SNAPSHOT:3ec223e:1412 by SpigotMC
13:47:30 [信息] Enabled plugin BungeeKick version 1.2 by Vik1395
13:47:30 [信息] [KnapsackToGo] 开始加载数据管理器！
13:47:30 [信息] [KnapsackToGo] ----------------------------
13:47:30 [信息] [KnapsackToGo] 下面是同步文件夹信息：
13:47:30 [信息] [KnapsackToGo] 数据保存路径是:C:\KnapsackToGo2.Data
13:47:30 [信息] [KnapsackToGo] ----------------------------
13:47:30 [信息] [KnapsackToGo] 数据管理器加载完成！
13:47:30 [信息] Enabled plugin KnapsackToGo version 2021.5.22 by jianjianai
13:47:30 [信息] Enabled plugin cmd_server version git:cmd_server:1.14-SNAPSHOT:3ec223e:1412 by SpigotMC
13:47:30 [信息] Enabled plugin cmd_alert version git:cmd_alert:1.14-SNAPSHOT:3ec223e:1412 by SpigotMC
13:47:30 [信息] Enabled plugin cmd_send version git:cmd_send:1.14-SNAPSHOT:3ec223e:1412 by SpigotMC
13:47:30 [信息] Enabled plugin cmd_list version git:cmd_list:1.14-SNAPSHOT:3ec223e:1412 by SpigotMC
13:47:30 [严重] [统一通行证] transform [https://api.mojang.com/profiles/minecraft] to [https://auth2.nide8.com:233/d857d2fdb1e311e89250525400b59b6a/api/profiles/minecraft]
13:47:30 [严重] [统一通行证] transform [https://sessionserver.mojang.com/session/minecraft/profile/] to [https://auth2.nide8.com:233/d857d2fdb1e311e89250525400b59b6a/sessionserver/session/minecraft/profile/]
13:47:30 [严重] [统一通行证] transform codecrafter47.bungeetablistplus.managers.SkinManagerImpl using yggdrasil-api-transform
13:47:30 [信息] [BungeeTabListPlus] Loading default - 副本.yml
13:47:30 [信息] [BungeeTabListPlus] Loading default.yml
13:47:30 [信息] Enabled plugin BungeeTabListPlus version 2.8.10 by CodeCrafter47
13:47:31 [信息] Listening on /0.0.0.0:26666
13:48:29 [信息] [BungeeSK] New server connected under name lobby with adress 127.0.0.1
13:50:12 [信息] [BungeeSK] New server connected under name safe with adress 127.0.0.1
13:50:23 [信息] [BungeeSK] New server connected under name war with adress 127.0.0.1
13:52:27 [信息] [/127.0.0.1:54889] <-> InitialHandler has connected
13:52:29 [信息] [danke] <-> InitialHandler has connected
13:52:29 [信息] [danke] <-> ServerConnector [Lobby] has connected
13:52:30 [信息] [danke] disconnected with: Kicked whilst connecting to Lobby: You are not whitelisted on this server!
13:52:30 [信息] [danke] <-> ServerConnector [Lobby] has disconnected
13:52:30 [信息] [danke] -> UpstreamBridge has disconnected
13:53:02 [信息] [/127.0.0.1:54935] <-> InitialHandler has connected
13:53:04 [信息] [danke] <-> InitialHandler has connected
13:53:05 [信息] [danke] <-> ServerConnector [Lobby] has connected
13:53:05 [信息] [danke] disconnected with: Kicked whilst connecting to Lobby: You are not whitelisted on this server!
13:53:05 [信息] [danke] <-> ServerConnector [Lobby] has disconnected
13:53:05 [信息] [danke] -> UpstreamBridge has disconnected
13:53:17 [信息] [danke] <-> InitialHandler has connected
13:53:18 [信息] [danke] <-> ServerConnector [Lobby] has connected
13:53:18 [警告] Error dispatching event ServerSwitchEvent(player=danke) to listener fr.zorg.bungeesk.bungee.listeners.ServSwitchEvent@f627d13
java.lang.NoSuchMethodError: net.md_5.bungee.api.event.ServerSwitchEvent.getFrom()Lnet/md_5/bungee/api/config/ServerInfo;
    at fr.zorg.bungeesk.bungee.listeners.ServSwitchEvent.onSwitch(ServSwitchEvent.java:13)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:397)
    at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:291)
    at net.md_5.bungee.protocol.packet.Login.handle(Login.java:87)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:104)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
    at java.lang.Thread.run(Unknown Source)
13:53:18 [信息] Netty is not using direct IO buffers.
13:53:44 [信息] [danke] <-> ServerConnector [war] has connected
13:53:45 [警告] Error dispatching event ServerSwitchEvent(player=danke) to listener fr.zorg.bungeesk.bungee.listeners.ServSwitchEvent@f627d13
java.lang.NoSuchMethodError: net.md_5.bungee.api.event.ServerSwitchEvent.getFrom()Lnet/md_5/bungee/api/config/ServerInfo;
    at fr.zorg.bungeesk.bungee.listeners.ServSwitchEvent.onSwitch(ServSwitchEvent.java:13)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:397)
    at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:291)
    at net.md_5.bungee.protocol.packet.Login.handle(Login.java:87)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:104)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
    at java.lang.Thread.run(Unknown Source)
13:53:45 [信息] [danke] <-> DownstreamBridge <-> [Lobby] has disconnected
13:54:11 [信息] [danke] <-> ServerConnector [safe] has connected
13:54:11 [警告] Error dispatching event ServerSwitchEvent(player=danke) to listener fr.zorg.bungeesk.bungee.listeners.ServSwitchEvent@f627d13
java.lang.NoSuchMethodError: net.md_5.bungee.api.event.ServerSwitchEvent.getFrom()Lnet/md_5/bungee/api/config/ServerInfo;
    at fr.zorg.bungeesk.bungee.listeners.ServSwitchEvent.onSwitch(ServSwitchEvent.java:13)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:397)
    at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:291)
    at net.md_5.bungee.protocol.packet.Login.handle(Login.java:87)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:104)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
    at java.lang.Thread.run(Unknown Source)
13:54:11 [信息] [danke] <-> DownstreamBridge <-> [war] has disconnected
13:56:20 [信息] [danke] <-> ServerConnector [Lobby] has connected

**Comment by ZorgBtw** [comment]
no i mean like how could i remake this bug on my own ?

**Comment by xibo1212** [comment]
> no i mean like how could i remake this bug on my own ?

I'm a Chinese and I don't understand English very well. Excuse me. Every time I log in or cross server after connecting, I will report an error. Is it my server problem? All my servers are stable versions of spigot. What do I need to do to make you copy this bug? Copy server file?

**Comment by ZorgBtw** [comment]
no you don't need to. you just have to update your bungeecord server (by, for example, downloading it in here: https://ci.md-5.net/job/BungeeCord/lastSuccessfulBuild/artifact/bootstrap/target/BungeeCord.jar)
you got this bug because you are using an older version of bungeecord

**Comment by xibo1212** [comment]
> no you don't need to. you just have to update your bungeecord server (by, for example, downloading it in here: https://ci.md-5.net/job/BungeeCord/lastSuccessfulBuild/artifact/bootstrap/target/BungeeCord.jar)
> you got this bug because you are using an older version of bungeecord

OK, thank you very much. It's really a little old, but the upgrade may need to update the configuration file, so I'm lazy. I'll try to upgrade the version later
