### ISSUE TITLE
Error BungeeSk - Disconnect From Proxy

### ISSUE THREAD

**Issue by SniperTVmc** [ZorgBtw/BungeeSK#17]
**Describe the bug**
I can connect the client to the proxy but when I then reconnect to the server I get this error and I am disconnected (from proxy with bungeeSK) at the lobby but not on the proxy side.

**To Reproduce**
- Connect BungeeSK to proxy
- And connect a player to the server.

**Expected behavior**

**Screenshots**
```
[12:42:22 ERROR]: Exception in thread "Thread-56" java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.api.connection.Server.getInfo()" because the return value of "net.md_5.bungee.api.connection.ProxiedPlayer.getServer()" is null
[12:42:22 ERROR]:       at fr.zorg.bungeesk.bungee.sockets.ClientServer.read(ClientServer.java:398)
[12:42:22 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
```

**Desktop (please complete the following information):**
 - OS: Debian 11 x64
 - Spigot version: Paper 1.9.4
 - BungeeSK version: 1.1.0
 - Java version: 16

**Comment by ZorgBtw** [comment]
Should be fixed in v2.0.0, download it [here](https://github.com/ZorgBtw/BungeeSK/suites/7627250624/artifacts/316917511)
