### ISSUE TITLE
BungeeSk v2 isn't loading

### ISSUE THREAD

**Issue by realago** [ZorgBtw/BungeeSK#22]
I am using the BungeeSk plugin you gave me in my other report, and it was working fine now it isn't :/

I literally have no idea why it isn't working now but it says it encountered an exception.

Error:
>[12:36:11 WARN]: Exception encountered when loading plugin: BungeeSK
java.lang.ClassCastException: class [Ljava.lang.String; cannot be cast to class java.util.ArrayList ([Ljava.lang.String; and java.util.ArrayList are in module java.base of loader 'bootstrap')
        at fr.zorg.bungeesk.bungee.BungeeConfig.getList(BungeeConfig.java:45) ~[?:?]
        at fr.zorg.bungeesk.bungee.packets.PacketServer.start(PacketServer.java:27) ~[?:?]
        at fr.zorg.bungeesk.bungee.BungeeSK.onEnable(BungeeSK.java:27) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:356) ~[Bungee.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:9e59de4:unknown]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:320) ~[Bungee.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:9e59de4:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:54) ~[Bungee.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:9e59de4:unknown]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[Bungee.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:9e59de4:unknown]<

**Comment by ZorgBtw** [comment]
Take [this version](https://github.com/ZorgBtw/BungeeSK/suites/7961916801/artifacts/340249922) instead, i fixed this problem in between

**Comment by realago** [comment]
Okay thank you

**Comment by Agomc** [comment]
Uhm, sorry I should probably use it before closing the report, because the same error came up...


`[12:44:19 WARN]: Exception encountered when loading plugin: BungeeSK
java.lang.ClassCastException: class [Ljava.lang.String; cannot be cast to class java.util.ArrayList ([Ljava.lang.String; and java.util.ArrayList are in module java.base of loader 'bootstrap')
        at fr.zorg.bungeesk.bungee.BungeeConfig.getList(BungeeConfig.java:47) ~[?:?]
        at fr.zorg.bungeesk.bungee.packets.PacketServer.start(PacketServer.java:29) ~[?:?]
        at fr.zorg.bungeesk.bungee.BungeeSK.onEnable(BungeeSK.java:28) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:356) ~[Bungee.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:9e59de4:unknown]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:320) ~[Bungee.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:9e59de4:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:54) ~[Bungee.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:9e59de4:unknown]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[Bungee.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:9e59de4:unknown]`

**Comment by ZorgBtw** [comment]
Could you please try this version
[BungeeSK.zip](https://github.com/ZorgBtw/BungeeSK/files/9418020/BungeeSK.zip)
?

**Comment by realago** [comment]
yes sorry lmao

**Comment by realago** [comment]
So the Bungeecord one works, but the Spigot one doesn't. It says:

>An error occurred during the server's launching process. 
Is the port opened ? Is the port available and not occupied by another process ?<

My server's are running off of different machines, do I put the port with the ip or just the ip?

**Comment by Agomc** [comment]
Wait I got it nevermind, the port was at default and must of been in use. Now it works thank you :)

**Comment by ZorgBtw** [comment]
Thank you too for your help about this issue ! 😄

**Comment by realago** [comment]
Bro I'm sorry this is making no sense lmao - from above how do I know what port is open and closed? I've changed the port multiple times and tried to run it on a same machine but still doesn't work, only the Bungeecord works now...

**Comment by ZorgBtw** [comment]
can you try follow up [this guide](https://bungeesk.zorgdev.fr) ?

**Comment by realago** [comment]
I tried all of that and it still doesn't work. What port should I be using, default or do I choose something random?

**Comment by ZorgBtw** [comment]
whatever as long as it's open

**Comment by realago** [comment]
How do I know if it's open?

**Comment by realago** [comment]
Cause every random port I try is apparently closed

**Comment by ZorgBtw** [comment]
are you under pterodactyl or running it locally?

**Comment by realago** [comment]
I was doing it locally but then I switched to pterodactyl and I have a new error:

>[13:20:01 WARN]: java.io.EOFException
[13:20:01 WARN]:        at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2926)
[13:20:01 WARN]:        at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3421)
[13:20:01 WARN]:        at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:959)
[13:20:01 WARN]:        at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:397)
[13:20:01 WARN]:        at BungeeSK.jar//fr.zorg.bungeesk.bukkit.packets.SocketClient.<init>(SocketClient.java:29)
[13:20:01 WARN]:        at BungeeSK.jar//fr.zorg.bungeesk.bukkit.packets.PacketClient.lambda$start$0(PacketClient.java:23)
[13:20:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)<

**Comment by ZorgBtw** [comment]
oh so for pterodactyl you need to have the port opened (check in the network section, on our bungeecord server) and need to put the public ip address to make it work

**Comment by realago** [comment]
I see now, I did that but had the network on my Hub server, not the Bungee, thank you for your help, it's just that locally it doesn't work for me :/

**Comment by ZorgBtw** [comment]
but did you changed your ip to something like 127.0.0.1 when running it locally?

**Comment by realago** [comment]
I tried it on the same and different machines. Both didn't work

**Comment by ZorgBtw** [comment]
and what about all under pterodactyl ? and btw, was it working before opening this issue?

**Comment by realago** [comment]
So I was never using Pterodactyl until you told me to, but everything was working fine a few days ago, but this morning it wasn't. So the local doesn't work for me at least when I'm on the same or different machines, but it does work for Pterodactyl. And I needed to set up the Networking through BungeeCord's, not a backend server (Ex: Hub).

**Comment by ZorgBtw** [comment]
can you please send again the errors that you get?

**Comment by realago** [comment]
This is from putting that old BungeeSk file into Bungeecord

>[12:36:11 WARN]: Exception encountered when loading plugin: BungeeSK
java.lang.ClassCastException: class [Ljava.lang.String; cannot be cast to class java.util.ArrayList ([Ljava.lang.String; and java.util.ArrayList are in module java.base of loader 'bootstrap')
at fr.zorg.bungeesk.bungee.BungeeConfig.getList(BungeeConfig.java:45) ~[?:?]
at fr.zorg.bungeesk.bungee.packets.PacketServer.start(PacketServer.java:27) ~[?:?]
at fr.zorg.bungeesk.bungee.BungeeSK.onEnable(BungeeSK.java:27) ~[?:?]
at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:356) ~[Bungee.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:9e59de4:unknown]
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:320) ~[Bungee.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:9e59de4:unknown]
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:54) ~[Bungee.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:9e59de4:unknown]
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[Bungee.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:9e59de4:unknown]

And this is from the Spigot server when I try and locally connect BungeeSk together:
>An error occurred during the server's launching process.
Is the port opened ? Is the port available and not occupied by another process ?

Finally, this error is from putting the Network into a Spigot/Paper server instead of Bungee for connecting using Pterodactyl:
>[13:20:01 WARN](https://github.com/ZorgBtw/BungeeSK/issues/java.io.EOFException): at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2926)
[13:20:01 WARN](https://github.com/ZorgBtw/BungeeSK/issues/java.io.EOFException): at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3421)
[13:20:01 WARN](https://github.com/ZorgBtw/BungeeSK/issues/java.io.EOFException): at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:959)
[13:20:01 WARN](https://github.com/ZorgBtw/BungeeSK/issues/java.io.EOFException): at java.base/java.io.ObjectInputStream.(ObjectInputStream.java:397)
[13:20:01 WARN](https://github.com/ZorgBtw/BungeeSK/issues/java.io.EOFException): at BungeeSK.jar//fr.zorg.bungeesk.bukkit.packets.SocketClient.(SocketClient.java:29)
[13:20:01 WARN](https://github.com/ZorgBtw/BungeeSK/issues/java.io.EOFException): at BungeeSK.jar//fr.zorg.bungeesk.bukkit.packets.PacketClient.lambda$start$0(PacketClient.java:23)
[13:20:01 WARN](https://github.com/ZorgBtw/BungeeSK/issues/java.io.EOFException): at java.base/java.lang.Thread.run(Thread.java:833)

And I think those are all the errors :)

**Comment by ZorgBtw** [comment]
when you are trying to run everything locally, is the port high enough (> 1000 at least, first ports are dedicated for internal purposes) ?
when you're trying to run everything locally, is the ip a local ip address (127.0.0.1, 0.0.0.0 or localhost) ?
and for the last error i think the first line is missing, so i can't really determine which type of error is it
