### ISSUE TITLE
An error will be reported when you start the server with the version you gave me a few days ago

### ISSUE THREAD

**Issue by xibo1212** [ZorgBtw/BungeeSK#25]
No errors were reported in the previous version v1.1.0

This use BungeeSK v2.0.0 :

[06:48:12] [Server thread/WARN]: [Skript] Task #8 for Skript v2.2-dev37c generated an exception
java.lang.AbstractMethodError: ch.njol.skript.classes.Parser.getVariableNamePattern()Ljava/lang/String;
	at ch.njol.skript.lang.VariableString.checkVariableConflicts(VariableString.java:334) ~[?:?]
	at ch.njol.skript.lang.VariableString.newInstance(VariableString.java:297) ~[?:?]
	at ch.njol.skript.lang.Variable.newInstance(Variable.java:154) ~[?:?]
	at ch.njol.skript.lang.SkriptParser.parseVariable(SkriptParser.java:279) ~[?:?]
	at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:295) ~[?:?]
	at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:625) ~[?:?]
	at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:800) ~[?:?]
	at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1530) ~[?:?]
	at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1487) ~[?:?]
	at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225) ~[?:?]
	at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180) ~[?:?]
	at ch.njol.skript.lang.Statement.parse(Statement.java:59) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:972) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:664) ~[?:?]
	at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:391) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:403) ~[?:?]
	at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:333) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:363) ~[?:?]
	at ch.njol.skript.Skript$2.run(Skript.java:472) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1648.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2-R0.1-SNAPSHOT-b1648.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2-R0.1-SNAPSHOT-b1648.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2-R0.1-SNAPSHOT-b1648.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2-R0.1-SNAPSHOT-b1648.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2-R0.1-SNAPSHOT-b1648.jar:git-Spigot-642f6d2-57ab4cf]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

**Comment by xibo1212** [comment]
In my test, I found that errors will be reported when %event-bungeeplayer% is placed in variables, such as:

```
on bungee player leave:
    add 1 to {_player_%event-bungeeplayer%}
```

**Comment by ZorgBtw** [comment]
First, update your Skript version. You are currently under the v2.2 which in very old.
Moreover, bungeeplayers are not meant to be stored in variables or in others ways such as databases. If you want to store bungeeplayer's data, you can use their name, their uuid and so on, but not the raw `bungeeplayer` type

**Comment by xibo1212** [comment]
> First, update your Skript version. You are currently under the v2.2 which in very old. Moreover, bungeeplayers are not meant to be stored in variables or in others ways such as databases. If you want to store bungeeplayer's data, you can use their name, their uuid and so on, but not the raw `bungeeplayer` type

oh, you are right, i get it ,thank you!
